name: schedule-codex

services:
  api:
    container_name: api
    ports:
      - "${API_PORT}:${API_PORT}"
    build:
      context: ../
      dockerfile: docker/dockerfile
    env_file: ../.env
    environment:
      - TZ=Asia/Tokyo
    entrypoint: ["bun", "src/index.ts"]
    restart: always
